import 'package:flutter/material.dart';

void main() {
  runApp(const startingPage());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class startingPage extends StatelessWidget {
  const startingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HomePage(),
        ]),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 415,
          height: 922,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 415,
                  height: 922,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(60),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 625,
                child: SizedBox(
                  width: 327,
                  height: 43,
                  child: Text(
                    'Track your Active Lifestyle',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 132,
                top: 668,
                child: Text(
                  'Journey to Wellness',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 726,
                child: Container(
                  width: 10,
                  height: 10,
                  decoration: ShapeDecoration(
                    color: Color(0xFFC4C4C4),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 211,
                top: 726,
                child: Container(
                  width: 10,
                  height: 10,
                  decoration: ShapeDecoration(
                    color: Color(0xFFC4C4C4),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 230,
                top: 726,
                child: Container(
                  width: 11,
                  height: 10,
                  decoration: ShapeDecoration(
                    color: Color(0xFFC4C4C4),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 164,
                top: 726,
                child: Container(
                  width: 20,
                  height: 10,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD42E2E),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(7)),
                  ),
                ),
              ),
              Positioned(
                left: 117,
                top: 783,
                child: Container(
                  width: 188,
                  height: 66,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD42E2E),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 159,
                top: 803,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'Get Started',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 144,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Flex',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 53,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                      TextSpan(
                        text: 'Yatra',
                        style: TextStyle(
                          color: Color(0xFFD42E2E),
                          fontSize: 53,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 73,
                top: 284,
                child: Container(
                  width: 269,
                  height: 269,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/269x269"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 3,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0xFFD42E2E),
                      ),
                      borderRadius: BorderRadius.circular(360),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}