// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEEnHf_DRzSjBVfx2zY3-pcJmSSoIatW4',
    appId: '1:636757632342:web:b7f76e09adcccbe96322f7',
    messagingSenderId: '636757632342',
    projectId: 'loginapp-3639e',
    authDomain: 'loginapp-3639e.firebaseapp.com',
    storageBucket: 'loginapp-3639e.appspot.com',
    measurementId: 'G-XM0ZLCD2KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu7gtTxOWJG_K98C_-wl3uB2lJlkzyHYc',
    appId: '1:636757632342:android:2365fe02bc87049e6322f7',
    messagingSenderId: '636757632342',
    projectId: 'loginapp-3639e',
    storageBucket: 'loginapp-3639e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDKwj_PsCy7awYI_SFzxg3bLkttvMO6Y',
    appId: '1:636757632342:ios:9a42bcf5c35ec0656322f7',
    messagingSenderId: '636757632342',
    projectId: 'loginapp-3639e',
    storageBucket: 'loginapp-3639e.appspot.com',
    iosBundleId: 'com.flexyatra.flexyatra',
  );
}
